### PR TITLE
Implemented DevLaunchersPlugin for ByteEconomy

### PR DESCRIPTION
**Pull request by Zorro909**
Loads Byte Item via DevLauncherConfiguration and registers it with the ItemRepository

### CODE REVIEW

**Comment by pyxld-kris** [comment]
@Zorro909 Hey Zorro, looking at the code this is awesome! I'm having some trouble getting it to run on my end unfortunately though. It could very well be something I'm doing, so I'll let you know the steps I'm taking.

1) Pulled the code from your branch to my local machine
2) Built it to my plugins folder
3) Pulled a copy of the dev-launchers-library jar into the same plugins folder (from the latest release on github)
4) Started the server

Upon starting the server, I get this error:
image

Do you have any idea what could be going wrong?

**Comment by Zorro909** [comment]
@pyxld-kris The first error is expected, since DevLaunchersLibrary is not a Plugin itself currently (gonna change that soon)
However I thought Maven was setup to shade the dependencies, so that it would contain the library in ByteEconomy, but yeah, I'll make the Library a Plugin and then it should be fine.

**Comment by Zorro909** [comment]
This Pull Request will also up the ByteEconomy Version to 0.0.3

**Comment by Zorro909** [comment]
PR #9 should be merged into this PR first, once everything is tested.

**Pull request merged**
